# Generated by Django 5.1.7 on 2025-05-26 18:14

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="about_me",
            field=models.CharField(
                blank=True,
                help_text="Tell us a bit about yourself (optional)",
                max_length=140,
                verbose_name="about me",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                help_text="Users that this user is following",
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="following",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_seen",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="last seen"
            ),
        ),
    ]
